#!/usr/bin/env bash

# --- Homebrew and Core Packages ---

if [ "$(uname -s)" = "Darwin" ]; then

    # install homebrew if it's missing
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing Homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    # install packages from .Brewfile
    if [ -f "$HOME/.Brewfile" ]; then
        echo "Installing Brew Packages"
        brew bundle --global
    fi

fi